# Generated by Django 3.0.7 on 2021-04-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210424_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='503', max_length=10, verbose_name='Código de país'),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(default='lag-icon flag-icon-slv', max_length=10, verbose_name='Bandera'),
        ),
    ]
